### ISSUE TITLE
Versão Antiga 

### ISSUE THREAD

**Issue by AlexsanderPH** [sidneypepo/to_install#1]
Esse Shell é pra instalar a interface xfce4 na versão antiga do Kali automaticamente ?, ao invés de baixar a .ISO atualizada ou atualizar ele direto com : 
```
sudo apt-get distro-upgrade
```

Versão do meu Kali : 2016.2; e não to afim de atualizar com um tanto de comando nem baixar outra .ISO

**Comment by sidneypepo** [comment]
> Esse Shell é pra instalar a interface xfce4 na versão antiga do Kali automaticamente ?, ao invés de baixar a .ISO atualizada ou atualizar ele direto com :
> 
> ```
> sudo apt-get distro-upgrade
> ```
> 
> Versão do meu Kali : 2016.2; e não to afim de atualizar com um tanto de comando nem baixar outra .ISO

Opa o/
Na verdade, esse repositório eu criei apenas como se fosse uma "to do list" de coisas que eu preciso instalar sempre que formato meu Kali Linux. Eu havia criado este repositório recentemente quando necessitei formatá-lo e esqueci de apagar e/ou criar uma lista em um bloco de notas com o que eu necessito instalar após um wipe no sistema.

Caso você deseje atualizar seu sistema, o único comando que você necessita executar é:
```sh
sudo apt update -y; sudo apt upgrade -y; sudo apt dist-upgrade -y
```

Ao atualizar, o sistema estará em sua versão mais atual (2020.4), porém ainda na interface GNOME. Caso deseje trocar para a interface padrão atual (XFCE), [siga este guia](https://www.kali.org/docs/general-use/xfce-faq/), ou execute os seguintes comandos:
```sh
sudo apt update -y; sudo apt install -y kali-desktop-xfce; update-alternatives --config x-session-manager; sudo apt purge --autoremove kali-desktop-gnome
```
